src/objects/Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Added_By__c</fullName>
        <label>Added By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Added__c</fullName>
        <label>Date Added</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mapping_Types__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mapping Types</label>
        <referenceTo>Mapping_Types__c</referenceTo>
        <relationshipLabel>Mappings</relationshipLabel>
        <relationshipName>Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SF_Field_Name__c</fullName>
        <label>SF Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Object_Name__c</fullName>
        <label>SF Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XTRAC_Field__c</fullName>
        <label>XTRAC Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping</label>
    <nameField>
        <label>Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mapping_Types__c.object
<CustomObject>
    <label>Mapping Types</label>
    <nameField>
        <label>Mapping Types Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MappingTypeListScreen_AC.cls
public with sharing class MappingTypeListScreen_AC {
 
 public String selectedMappingId{get;set;}
 public String mappingType {get;set;}
 public list<Mapping__c> lstMapping {get;set;}
 
 public MappingTypeListScreen_AC(){
 	mappingType = ApexPages.CurrentPage().getParameters().get('mappingtype');
 	fetchMapping();
 }
 
 private void fetchMapping(){
 	lstMapping = [Select Id,SF_Object_Name__c,SF_Field_Name__c,XTRAC_Field__c,Added_By__c,Date_Added__c From Mapping__c Where Mapping_Types__r.Name = :mappingType];
 }
 
 public void delMapping(){
 	delete new Mapping__c(Id=selectedMappingId);
 	fetchMapping();
 }
 
}