src/objects/oAuth2Service__c.object
<CustomObject>
    <fields>
        <fullName>Service_Identifier__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Service Identifier</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>oAuth2Service</label>
    <nameField>
        <label>oAuth2Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oAuth2Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/oAuth2Token__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Identifier__c</fullName>
        <formula>oAuth2Service__r.Service_Identifier__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>oAuth2Tokens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>oAuth2Service__c</fullName>
        <label>oAuth2Service</label>
        <referenceTo>oAuth2Service__c</referenceTo>
        <relationshipLabel>oAuth2Tokens</relationshipLabel>
        <relationshipName>oAuth2Tokens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>oAuth2Token</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>oAuth2Token Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>oAuth2Tokens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OAuth.cls
public with sharing class OAuth {
  public PageReference completeAuthorization() {
  	String serviceIdentifier = ApexPages.currentPage().getParameters().get('sIdentifier');
    String code = ApexPages.currentPage().getParameters().get('code');    
    
    if(serviceIdentifier == null || serviceIdentifier == ''){
    	serviceIdentifier = 'Google_Calendar';
    }
    
    if(code != '' && code != null){
    	list<oAuth2Token__c> lstToken = [SELECT Id,Code__c FROM oAuth2Token__c Where oAuth2Service__r.Service_Identifier__c =:serviceIdentifier and User__c=:userInfo.getUserId() limit 1];
    	oAuth2Token__c oAT;
    	if(lstToken.size()>0){
    		oAT = lstToken[0];
    		oAT.Code__c = code;
        update oAT;
    	}
    	else{
    		oAuth2Service__c oA = [Select Id From oAuth2Service__c Where Service_Identifier__c =:serviceIdentifier limit 1];
    		oAT = new oAuth2Token__c();
    		oAT.oAuth2Service__c = oA.Id;
    		oAT.Code__c = code;
    		oAT.User__c = userinfo.getUserId();
    		insert oAT;
    	}
    }
    return new PageReference('/apex/authTest?sIdentifier='+serviceIdentifier);
  }
}